spring:
  security:
    user:
      name: drone
      password: drone

  datasource:
    name: drone-app
    driver-class-name: org.postgresql.Driver
    username: drone
    password: drone
    url: jdbc:postgresql://localhost:7777/drone-db?currentSchema=public
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        id:
          new_generator_mappings: true
    show-sql: false
    open-in-view: true

  profiles:
    active: dev

  application:
    name: DRONE-SERVICE

logging:
  level:
    .: warn
    org:
      springframework:
        boot: warn
        web: warn
    org.hibernate.SQL: warn

    com:
      drone-service:
        app:
          platform: info

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b %D'
      buffered: false
      prefix: stdout
      directory: logs
    basedir: tomcat
    threads:
      min-spare: 50
  servlet:
    context-path: /drone-app
  port: 8888

  endpoints:
    web:
      exposure:
        include: health, info, loggers
        exclude: env, beans