FROM openjdk:15-jdk-alpine
MAINTAINER https://www.linkedin.com/in/adewale-kolawole-whales/
COPY target/drone-app-0.0.1-SNAPSHOT.jar drone-app-0.0.1.jar
ENTRYPOINT ["java","-jar","/drone-app-0.0.1.jar"]